# Generated by Django 5.0.14 on 2025-08-02 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_stripecustomer_stripesubscription_stripepayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='display',
            name='activation_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='display',
            name='activation_status',
            field=models.CharField(choices=[('pending', 'Pending Activation'), ('active', 'Active'), ('inactive', 'Inactive'), ('blocked', 'Blocked')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='display',
            name='device_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='display',
            name='device_info',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='display',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('free', 'Free'), ('business', 'Business'), ('enterprise', 'Enterprise')], default='free', max_length=20),
        ),
    ]
