# Generated by Django 5.0.14 on 2025-08-02 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_display_activation_code_display_activation_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='display',
            name='registered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registered_displays', to=settings.AUTH_USER_MODEL),
        ),
    ]
