# Generated by Django 5.0.14 on 2025-08-02 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_display_registered_by'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='display',
            name='display_owner_xor',
        ),
        migrations.AddConstraint(
            model_name='display',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('activation_status', 'pending'), ('business__isnull', True), ('personal_user__isnull', True)), models.Q(('business__isnull', True), ('personal_user__isnull', False)), models.Q(('business__isnull', False), ('personal_user__isnull', True)), _connector='OR'), name='display_owner_xor'),
        ),
    ]
