# Generated by Django 5.0.14 on 2025-08-02 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_display_display_owner_xor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10),
        ),
    ]
