# Generated by Django 5.0.14 on 2025-08-02 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_media_media_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('total_impressions', models.IntegerField(default=0)),
                ('total_duration', models.IntegerField(default=0, help_text='Total seconds displayed')),
                ('is_active', models.BooleanField(default=True)),
                ('ended_reason', models.CharField(blank=True, max_length=50)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='api.campaign')),
                ('display', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_sessions', to='api.display')),
            ],
            options={
                'db_table': 'CampaignSessions',
                'indexes': [models.Index(fields=['display', '-started_at'], name='CampaignSes_display_b352c3_idx'), models.Index(fields=['campaign', '-started_at'], name='CampaignSes_campaig_2431c5_idx')],
            },
        ),
        migrations.CreateModel(
            name='DeviceHeartbeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('device_status', models.CharField(default='online', max_length=20)),
                ('device_info', models.JSONField(blank=True, default=dict)),
                ('current_campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.campaign')),
                ('display', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heartbeats', to='api.display')),
            ],
            options={
                'db_table': 'DeviceHeartbeats',
                'indexes': [models.Index(fields=['display', '-timestamp'], name='DeviceHeart_display_9b3057_idx')],
            },
        ),
        migrations.CreateModel(
            name='MediaImpression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('duration_shown', models.IntegerField(help_text='Actual seconds displayed')),
                ('scheduled_duration', models.IntegerField(help_text='Intended seconds from campaign')),
                ('completed', models.BooleanField(default=False)),
                ('sequence_number', models.IntegerField(help_text='Order in campaign rotation')),
                ('total_media_in_campaign', models.IntegerField()),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impressions', to='api.campaign')),
                ('display', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impressions', to='api.display')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impressions', to='api.media')),
            ],
            options={
                'db_table': 'MediaImpressions',
                'indexes': [models.Index(fields=['display', '-started_at'], name='MediaImpres_display_a95b4d_idx'), models.Index(fields=['campaign', '-started_at'], name='MediaImpres_campaig_11e88e_idx'), models.Index(fields=['media', '-started_at'], name='MediaImpres_media_i_05b431_idx')],
            },
        ),
    ]
