# Generated by Django 5.0.14 on 2025-08-03 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_campaignsession_deviceheartbeat_mediaimpression'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='has_advanced_analytics',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='has_advanced_scheduling',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='has_api_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='has_custom_branding',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='has_priority_support',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='has_video_support',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='max_campaigns',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='plan',
            name='max_displays',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='plan',
            name='max_images',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='plan',
            name='max_users',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='plan',
            name='max_videos',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='plan',
            name='currency',
            field=models.CharField(default='ZAR', max_length=10),
        ),
        migrations.AlterField(
            model_name='plan',
            name='max_screens',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='plan',
            name='max_storage_gb',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('free', 'Free'), ('starter', 'Starter'), ('professional', 'Professional'), ('enterprise', 'Enterprise')], default='free', max_length=20),
        ),
    ]
