# Generated by Django 5.0.14 on 2025-08-03 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_update_account_type_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready'), ('active', 'Active'), ('paused', 'Paused'), ('scheduled', 'Scheduled'), ('expired', 'Expired')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='campaign',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
