# Generated by Django 5.2.4 on 2025-08-04 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_add_campaign_status_scheduling'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='screen_orientation',
            field=models.CharField(choices=[('portrait', 'Portrait'), ('landscape', 'Landscape')], default='portrait', help_text='Orientation for all media in this campaign', max_length=10),
        ),
    ]
