# Generated by Django 5.0.9 on 2025-08-10 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_campaign_display_orientation_activation_ttl'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='preempt',
            field=models.BooleanField(default=False, help_text='If true, this schedule preempts other overlapping schedules regardless of priority'),
        ),
    ]
