# Generated by Django 5.2.4 on 2025-08-30 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_create_menu_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='last_pos_sync',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='pos_item_id',
            field=models.CharField(blank=True, help_text='External POS system item ID', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='promotion_flag',
            field=models.BooleanField(default=False, help_text='Item is currently on promotion'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='special_offer',
            field=models.CharField(blank=True, help_text='Promotional text from POS', max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Descriptive name for this API key', max_length=255)),
                ('key', models.CharField(help_text='The actual API key', max_length=255, unique=True)),
                ('can_update_menus', models.BooleanField(default=True)),
                ('can_read_analytics', models.BooleanField(default=False)),
                ('allowed_ips', models.TextField(blank=True, help_text='Comma-separated list of allowed IP addresses', null=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='api.business')),
            ],
            options={
                'db_table': 'ApiKeys',
            },
        ),
        migrations.CreateModel(
            name='POSIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos_system_type', models.CharField(choices=[('square', 'Square'), ('toast', 'Toast'), ('lightspeed', 'Lightspeed'), ('shopify', 'Shopify POS'), ('generic', 'Generic API')], max_length=50)),
                ('api_endpoint', models.URLField(blank=True, null=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('sync_status', models.CharField(choices=[('active', 'Active'), ('error', 'Error'), ('disabled', 'Disabled'), ('pending', 'Pending Setup')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('sync_interval_minutes', models.PositiveIntegerField(default=30)),
                ('auto_sync_enabled', models.BooleanField(default=True)),
                ('webhook_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pos_integrations', to='api.business')),
            ],
            options={
                'db_table': 'POSIntegrations',
            },
        ),
        migrations.CreateModel(
            name='MenuItemPOSSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos_item_id', models.CharField(max_length=100)),
                ('last_pos_update', models.DateTimeField(auto_now=True)),
                ('sync_conflicts', models.JSONField(default=dict, help_text='Conflicts between POS and local data')),
                ('pos_name', models.CharField(blank=True, max_length=255, null=True)),
                ('pos_description', models.TextField(blank=True, null=True)),
                ('pos_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pos_available', models.BooleanField(default=True)),
                ('pos_promotion_data', models.JSONField(default=dict)),
                ('menu_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pos_sync', to='api.menuitem')),
                ('pos_integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_syncs', to='api.posintegration')),
            ],
            options={
                'db_table': 'MenuItemPOSSync',
                'unique_together': {('pos_integration', 'pos_item_id')},
            },
        ),
        migrations.CreateModel(
            name='POSUpdateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_type', models.CharField(choices=[('webhook', 'Webhook'), ('manual', 'Manual Sync'), ('scheduled', 'Scheduled Sync'), ('api', 'API Update')], max_length=20)),
                ('items_updated', models.PositiveIntegerField(default=0)),
                ('items_failed', models.PositiveIntegerField(default=0)),
                ('update_data', models.JSONField(default=dict)),
                ('error_details', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('pos_integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='update_logs', to='api.posintegration')),
            ],
            options={
                'db_table': 'POSUpdateLogs',
                'indexes': [models.Index(fields=['pos_integration', '-timestamp'], name='POSUpdateLo_pos_int_f9fa8a_idx')],
            },
        ),
    ]
