# Generated by Django 5.0.14 on 2025-08-30 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_menuitem_last_pos_sync_menuitem_pos_item_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='auto_refresh_seconds',
            field=models.PositiveIntegerField(default=10, help_text='Auto-refresh interval for menu content'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='campaign_type',
            field=models.CharField(choices=[('media', 'Media Campaign'), ('menu', 'Menu Campaign'), ('hybrid', 'Hybrid Campaign')], default='media', max_length=10),
        ),
        migrations.AddField(
            model_name='campaign',
            name='featured_rotation_seconds',
            field=models.PositiveIntegerField(default=8, help_text='Featured item rotation interval'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='menu',
            field=models.ForeignKey(blank=True, help_text='Menu to display for menu campaigns', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='api.menu'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='menu_layout',
            field=models.CharField(choices=[('single', 'Single Screen'), ('dual', 'Dual Screen'), ('triple', 'Triple Screen')], default='dual', help_text='Layout for menu display', max_length=10),
        ),
        migrations.AddField(
            model_name='campaign',
            name='promotional_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Metadata for auto-generated promotional campaigns'),
        ),
        migrations.AddConstraint(
            model_name='campaign',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('campaign_type', 'menu'), ('menu__isnull', False)), ('campaign_type__in', ['media', 'hybrid']), _connector='OR'), name='menu_campaign_requires_menu'),
        ),
    ]
