"""
Django settings for signage_project project.

Generated by 'django-admin startproject' using Django 5.0.14.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ue+j-y)eh@!@bw0)b9)0x&e!y49qkly*-m7j2v1w(10+6ktfoh'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'api',
    'drf_yasg',
]

# Custom user model
AUTH_USER_MODEL = 'api.User'

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
# CORS configuration - More permissive for development
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://localhost:3001", 
    "http://127.0.0.1:8080",
    "http://localhost:8080",
    "http://localhost:5173",  # Vite frontend
    "http://localhost:5174",  # Vite frontend alternate port
    "http://localhost:5175",  # Vite frontend alternate port
    "http://127.0.0.1:5173",  # Alternative localhost format
    "http://127.0.0.1:5174",  # Alternative localhost format
    "http://127.0.0.1:5175",  # Alternative localhost format
]

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_ALL_ORIGINS = True  # Allow all origins for development - change to False in production

# Additional CORS headers
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# CORS methods
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

# REST framework configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

# JWT configuration
from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
}

ROOT_URLCONF = 'signage_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'signage_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Media files (User uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --- Stripe Configuration ---
# TODO: Add your Stripe API keys here
# Get keys from: https://dashboard.stripe.com/test/apikeys
STRIPE_PUBLISHABLE_KEY = "pk_test_YOUR_PUBLISHABLE_KEY_HERE"  # Safe to expose in frontend
STRIPE_SECRET_KEY = "sk_test_YOUR_SECRET_KEY_HERE"  # Keep this secret!
STRIPE_WEBHOOK_SECRET = "whsec_YOUR_WEBHOOK_SECRET_HERE"  # For webhook verification

# Stripe Product IDs (create these in Stripe Dashboard)
# You'll need to create 2 products in Stripe Dashboard:
# 1. Business Plan - R99/month recurring
# 2. Enterprise Plan - R500/month recurring
STRIPE_BUSINESS_PLAN_PRICE_ID = "price_YOUR_BUSINESS_PLAN_PRICE_ID"  # R99/month
STRIPE_ENTERPRISE_PLAN_PRICE_ID = "price_YOUR_ENTERPRISE_PLAN_PRICE_ID"  # R500/month

# Payment settings
STRIPE_CURRENCY = 'zar'  # South African Rand

# Plan pricing (for display purposes)
PLAN_PRICING = {
    'free': {
        'name': 'Free',
        'price': 0,
        'currency': 'ZAR',
        'features': [
            'Up to 2 displays',
            'Basic media library',
            'Standard scheduling',
            'Email support',
            '1GB storage'
        ]
    },
    'business': {
        'name': 'Business',
        'price': 99.00,
        'currency': 'ZAR',
        'stripe_price_id': 'STRIPE_BUSINESS_PLAN_PRICE_ID',
        'features': [
            'Up to 25 displays',
            'Advanced media library',
            'Advanced scheduling',
            'Priority support',
            'Team collaboration',
            'Analytics dashboard',
            '50GB storage',
            'API access'
        ]
    },
    'enterprise': {
        'name': 'Enterprise',
        'price': 500.00,
        'currency': 'ZAR',
        'stripe_price_id': 'STRIPE_ENTERPRISE_PLAN_PRICE_ID',
        'features': [
            'Unlimited displays',
            'Custom integrations',
            'Dedicated support manager',
            'SLA guarantee',
            'White-label options',
            'Advanced analytics',
            'Unlimited storage',
            'Custom API endpoints',
            'Multi-tenant support'
        ]
    }
}
